### ISSUE TITLE
hedera suite manjaro repo

### ISSUE THREAD

**Issue by gericom-hummer** [sixsixfive/Hedera#1]
Hi there, just to mention, that i have started maintaining a hedera suite at my repo for manjaro distro: [http://download.tuxfamily.org/gericom/README.html]
and can be found here [http://download.tuxfamily.org/gericom/manjaro/]
if you want to mention it. I am updating it daily, as soon as you push the changes on git. 
Thanks.

**Comment by sixsixfive** [comment]
oh nice, also your version number is incorrect (I gave up on releases) you can find a more recent at the debian [changelog](https://github.com/sixsixfive/Hedera/blob/master/debian/changelog)

**Comment by gericom-hummer** [comment]
Nice, I will correct I later today. Thanks

**Comment by gericom-hummer** [comment]
Hi again. Just writing you to mention that the package i am maintaining at my manjaro repo, from today will be splitted into 13 separate packages, for each themed app. Thanks, and have a great holidays.
