### ISSUE TITLE
The panel of Hedera Darker display wrong battery and volume icons.

### ISSUE THREAD

**Issue by chuutatsu** [sixsixfive/Hedera#10]
Manjaro Xfce GTK 3.22 here. I used the latest version of Hedera and its icons from Github.

With Hedera (light) theme, all Hedera tray icons displayed correctly. 
![correct](https://user-images.githubusercontent.com/24815847/29486910-34575360-851b-11e7-80ad-5762964d7681.png)

Unfortunately, when I use Hedera Darker, the panel displayed wrong battery and volume icons similar to "hicolor" or "phlat" dark icons.
![wrong](https://user-images.githubusercontent.com/24815847/29486912-3c3a3b88-851b-11e7-97b8-bad68a073b86.png)

Please fix this issue. Thanks in advance.

**Comment by AnwarShah** [comment]
Sorry it's a bit off topic but how did you install the icons? I didn't find any. from Herera-icons repository, there was no built icon set and the compilation is being failed

**Comment by chuutatsu** [comment]
@AnwarShah I followed the instructions in hedera-icons github page. Make sure that you have installed the required dependencies for building the icons.

"SED, AWK, Inkscape & Convert {GNU parallel is strongly recommended"

After the process finished it will appear in /tmp folder. Copy it to the icons folder.

Please read carefully the github page again.

**Comment by AnwarShah** [comment]
@chuutatsu Thanks for the quick reply. I actually I have all those requirements filled. But surprisingly it's failing on this step. 

```
.
.
.
PNG optimization... DONE
converting for 16 failed - Aborting...
```

**Comment by sixsixfive** [comment]
i will look at it however i guess its an icon error, also xfce@gtk3 is alpha software so expect bugs

**Comment by chuutatsu** [comment]
Alright, I'll wait. 
Also, there is no any Xfce GTK3 packages in my machine right now.

**Comment by sixsixfive** [comment]
sorry but thats a xfce/gtk issue those 2 applications use GTK3, so if you change your xfce theme they should change too(to regular icons since the hedera theme foreces theme over symbolic icons) however for some weird reasons this wont work on gtk3 panel applets without a re-login. so they will still use the symboic icons by GTK and gtk will draw them with the themes font color in this case black.
