### ISSUE TITLE
Text in Terminal barely visible in Unity

### ISSUE THREAD

**Issue by happydemic** [sixsixfive/Hedera#4]
Unity, Ubuntu 16.10, gtk 3.20
Hedera 66cbaf6

The Hedera terminal background is set to black, and (at least for me) there seems to be no special font colour for terminal, meaning the font appears near-black as usual against a black background and is almost invisible (see below - username blacked out). 
![terminal hedera](https://cloud.githubusercontent.com/assets/12738878/21965781/a685a980-db5e-11e6-9cfc-679eb45bc03a.png)

The overall result has too little contrast to be usable on my system. Contrast Adapta, which uses a dark terminal background and has a light font colour for use in terminal only.

**Comment by sixsixfive** [comment]
weird, i dont have this issue with any of my installed terms

![screenshot_2017-01-15_23-36-43](https://cloud.githubusercontent.com/assets/3780774/21966848/af2ccf7e-db7b-11e6-8b09-5825eae4dff0.png)

maybe its some ubuntu specific issue due their hacked and patched packages - I guess i have to install ubuntu to find the issue (=

**Comment by happydemic** [comment]
So Unity breaks gtk in weird and unexpected ways? Shocking! </sarcasm> 

Thanks for offering to look at it.

**Comment by sixsixfive** [comment]
this should now work with the latest commit that includes https://github.com/sixsixfive/Hedera-src/commit/029a91e84a04f2bc8be69dd8e68186c3a9d9eeb5
