### ISSUE TITLE
[Request] Dark color scheme

### ISSUE THREAD

**Issue by frostheart** [sixsixfive/Hedera#5]
It would be great if you can add also a dark color scheme, 'cause dark tones are better for eyes, especially in the dark.

**Comment by sixsixfive** [comment]
no sorry, Hedera is made as a light theme(even if i would include a dark theme the icon theme is only usable at bright to grey colors)

its also horrible to maintain(i did this on my older [glare](http://sixsixfive.deviantart.com/art/Glare-494114516) theme but in the end it just was too complex to maintain)
