### ISSUE TITLE
Make theme possible to install without the icons packs

### ISSUE THREAD

**Issue by AnwarShah** [sixsixfive/Hedera#6]
I downloaded the theme's folder content and place in `~/.local/share/themes`, but it's not applying appropriately. I think, it's missing some resources. 

I'm requesting to make the theme and icon pack separate, so that anyone can choose without installing the other one.

**Comment by sixsixfive** [comment]
this is the case the theme can be used with any other traditional icon theme

**Comment by AnwarShah** [comment]
This theme doesn't work at all with manually downloading and putting the files in ~/.local/share/themes. And I don't want to download the whole repo master.zip file which includes the icons.

**Comment by sixsixfive** [comment]
Then you must have missed something. I have absolutely no idea what do you mean by "manually downloading" since this is a git repo and the only way to get things is with git or by downloading the master.zip. Github also supports subversion so you could do eg:

```
cd $HOME/.local/share/themes
svn co https://github.com/sixsixfive/Hedera/trunk/Other/themes .
```

**Comment by AnwarShah** [comment]
@sixsixfive I followed this and the themes are totally undecorated when selected in XFCE. As if you've applied old 'Religh' theme

**Comment by sixsixfive** [comment]
So you are talking about the gtk2 theme? make sure you have the correct gtk2-engines installed: it needs pixbuf/pixmap, murrine and mist(https://github.com/sixsixfive/Hedera#gtk2)

**Comment by AnwarShah** [comment]
Yes. I do have both pixbuf, murrine installed. Here is a screenshot of how the theme looks after installation https://snag.gy/K2PyBA.jpg

**Comment by sixsixfive** [comment]
strange what happens if you run an application from a terminal? if there is something missing it should print a lot of errors

**Comment by Lesik** [comment]
The same is happening for me on Xubuntu 17.04. All applications look like Windows 98.

The packages `gtk2-engines gtk2-engines-murrine gtk2-engines-pixbuf` are installed (`gtk2-engines` contains Mist), and I first tried applying the theme in the Xfce settings, then copied the GTK 2 and GTK 3 configuration files from the readme, no luck.
